id: I95019151
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:47:14+00:00'
last_modified: '2022-06-08T12:16:12.396537+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN545
  title: ཐུབ་བསྟན་གསེར་མདོག་ཅན་དགོན་གྱི་ཆོས་སྤྱོད་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    18DF:
      image_group_id: I3CN3916
      title: ''
      total_pages: 502
      order: 1
      base_file: 18DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
