id: P009613
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:40:46.805882
source_metadata:
  id: bdr:W3CN545
  title: ཐུབ་བསྟན་གསེར་མདོག་ཅན་དགོན་གྱི་ཆོས་སྤྱོད་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    1aff9bb9bba84a26b82b70220094221f:
      image_group_id: I3CN3916
      title: ''
      volume_number: 1
      total_pages: 502
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
